version: '3.8'
services: 
    app:
        build: 
            context: .
            dockerfile: api.Dockerfile
        container_name: "core-api-container"
        image: donghyun-compose:latest
        ports: 
            - 8000:8080
        volumes: 
            - ./app:/workspace/app